# Generated by Django 4.0.6 on 2022-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=255, verbose_name='Коментарий')),
            ],
        ),
    ]
